
language: node_js
node_js:
- "8"
- node

language: node_js
node_js:
  - "9"
dist: trusty
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
notifications:
  email: false